/** Country display name (as returned by as-ip) → ISO 3166-1 alpha-2. */
const countryNameToIsoCode: Record<string, string> = {
  Afghanistan: 'af',
  Albania: 'al',
  Algeria: 'dz',
  Andorra: 'ad',
  Angola: 'ao',
  Argentina: 'ar',
  Armenia: 'am',
  Australia: 'au',
  Austria: 'at',
  Azerbaijan: 'az',
  Bahrain: 'bh',
  Bangladesh: 'bd',
  Belarus: 'by',
  Belgium: 'be',
  Bolivia: 'bo',
  'Bosnia and Herzegovina': 'ba',
  Brazil: 'br',
  Bulgaria: 'bg',
  Cambodia: 'kh',
  Canada: 'ca',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  Croatia: 'hr',
  Cyprus: 'cy',
  'Czech Republic': 'cz',
  Czechia: 'cz',
  Denmark: 'dk',
  Ecuador: 'ec',
  Egypt: 'eg',
  Estonia: 'ee',
  Ethiopia: 'et',
  Finland: 'fi',
  France: 'fr',
  Georgia: 'ge',
  Germany: 'de',
  Ghana: 'gh',
  Greece: 'gr',
  'Hong Kong': 'hk',
  Hungary: 'hu',
  Iceland: 'is',
  India: 'in',
  Indonesia: 'id',
  Iran: 'ir',
  'Islamic Republic of Iran': 'ir',
  Iraq: 'iq',
  Ireland: 'ie',
  Israel: 'il',
  Italy: 'it',
  Japan: 'jp',
  Jordan: 'jo',
  Kazakhstan: 'kz',
  Kenya: 'ke',
  Kuwait: 'kw',
  Latvia: 'lv',
  Lebanon: 'lb',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Malaysia: 'my',
  Mexico: 'mx',
  Moldova: 'md',
  Mongolia: 'mn',
  Montenegro: 'me',
  Morocco: 'ma',
  Myanmar: 'mm',
  Nepal: 'np',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Nigeria: 'ng',
  'North Macedonia': 'mk',
  Norway: 'no',
  Oman: 'om',
  Pakistan: 'pk',
  Palestine: 'ps',
  Panama: 'pa',
  Peru: 'pe',
  Philippines: 'ph',
  Poland: 'pl',
  Portugal: 'pt',
  Qatar: 'qa',
  Romania: 'ro',
  Russia: 'ru',
  'Russian Federation': 'ru',
  'Saudi Arabia': 'sa',
  Serbia: 'rs',
  Singapore: 'sg',
  Slovakia: 'sk',
  Slovenia: 'si',
  'South Africa': 'za',
  'South Korea': 'kr',
  'Korea, Republic of': 'kr',
  Spain: 'es',
  'Sri Lanka': 'lk',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  Taiwan: 'tw',
  Thailand: 'th',
  Tunisia: 'tn',
  Turkey: 'tr',
  Türkiye: 'tr',
  Ukraine: 'ua',
  'United Arab Emirates': 'ae',
  'United Kingdom': 'gb',
  'United States': 'us',
  'United States of America': 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Venezuela: 've',
  Vietnam: 'vn',
  Yemen: 'ye',
}

export function resolveCountryIsoCode(countryName: string): string | null {
  const normalized = countryName.trim()
  if (!normalized) {
    return null
  }
  return countryNameToIsoCode[normalized] ?? null
}

export function buildCountryFlagUrl(countryName: string): string | null {
  const isoCode = resolveCountryIsoCode(countryName)
  if (!isoCode) {
    return null
  }
  return `https://flagcdn.com/48x36/${isoCode}.svg`
}
